import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google'
import Navbar from "./component/Navbar";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Next.js Tutorial",
  description: "Generated by create next app",
};
const inter = Inter({subsets: ["latin"]});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.variable} 
      >
        <Navbar/>
        <main className="px-8 py-20 max-w-6xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
